### ISSUE TITLE
Enum collection in yml now singular instead of plural

### ISSUE THREAD

**Issue by jjinkxy** [lwe/simple_enum#141]
I just want to double check, but in the 1.x version it was advised to name the enum collection in the plural form in the i18n yaml file eg.
``` yaml
de:
   enums:
     genders:
       female: 'Frau'
       male: 'Mann'
```

Now, for 2.x, its advised to name them in the singular form eg.
```yaml
de:
   enums:
     gender:
       female: 'Frau'
       male: 'Mann'
```
Is this correct? Otherwise the ViewHelpers wont work?

If so, could this be added to the [1.x-to-2.x-Migration-Guide](https://github.com/lwe/simple_enum/wiki/1.x-to-2.x-Migration-Guide)?
