### ISSUE TITLE
Unable to use specific locale file 

### ISSUE THREAD

**Issue by guillaumebesse** [lwe/simple_enum#7]
In my fr.yml file, I have

```
fr:
  activerecord:   
    enums:
      recipe:
        course_type:
          unkown: "Inconnu"
          amuse_bouche: "Amuse-bouche"
          entree: "Entrée"
          accompagnement: "Accompagnement"
          plat_principal: "Plat principal"
          dessert: "Dessert"
          sauce: "Sauce"
          boisson: "Boisson"
          base: "Base"
```

I want to use these translations with
    <%= select(:recipe, "course_type_enum", Recipe.course_types_for_select(:value)) %>

Is it supported ? 
Any help or advice welcome.
